// <auto-generated />
using DomPizza.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomPizza.Data.Migrations
{
    [DbContext(typeof(DomPizzaContext))]
    [Migration("20251110005714_SeedUsuarioInicial2")]
    partial class SeedUsuarioInicial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomPizza.Domain.Entities.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acao = "Ler",
                            Descricao = "Pode visualizar usuários",
                            Tipo = "Usuario"
                        },
                        new
                        {
                            Id = 2,
                            Acao = "Criar",
                            Descricao = "Pode criar usuários",
                            Tipo = "Usuario"
                        },
                        new
                        {
                            Id = 3,
                            Acao = "Editar",
                            Descricao = "Pode editar usuários",
                            Tipo = "Usuario"
                        },
                        new
                        {
                            Id = 4,
                            Acao = "Excluir",
                            Descricao = "Pode excluir usuários",
                            Tipo = "Usuario"
                        });
                });

            modelBuilder.Entity("DomPizza.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Acesso total ao sistema",
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Gestão de usuários e produtos",
                            Nome = "Operador"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Acesso somente leitura",
                            Nome = "Leitor"
                        });
                });

            modelBuilder.Entity("DomPizza.Domain.Entities.RolePermissao", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("RolePermissoes");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissaoId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissaoId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissaoId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PermissaoId = 1
                        });
                });

            modelBuilder.Entity("DomPizza.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "DomPizza@adm",
                            Nome = "Administrador DomPizza",
                            SenhaHash = "AQAAAAIAAYagAAAAEFyhC+iz5ABqnQQcYhzlmStnBaOGghPJOJPyK5jTrFo1Blt5ceMGtZ7+JuBSZ7daYg=="
                        });
                });

            modelBuilder.Entity("DomPizza.Domain.Entities.UsuarioRole", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("DomPizza.Domain.Entities.RolePermissao", b =>
                {
                    b.HasOne("DomPizza.Domain.Entities.Permissao", "Permissao")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomPizza.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DomPizza.Domain.Entities.UsuarioRole", b =>
                {
                    b.HasOne("DomPizza.Domain.Entities.Role", "Role")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomPizza.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DomPizza.Domain.Entities.Permissao", b =>
                {
                    b.Navigation("RolePermissoes");
                });

            modelBuilder.Entity("DomPizza.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissoes");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("DomPizza.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
